# Default UI Theme Configuration for grepctl
# This file can be customized and passed to the serve command:
# grepctl serve --theme-config ./custom-theme.yaml

branding:
  companyName: "grepctl"
  logo: "/grepctl_logo.png"
  favicon: "/favicon.ico"
  tagline: "Multimodal Semantic Search Platform"

colors:
  # Primary brand colors
  primary: "#1976d2"      # Main brand color
  secondary: "#dc004e"    # Secondary accent
  accent: "#9c27b0"       # Tertiary accent

  # Background colors
  background: "#ffffff"   # Main background
  surface: "#f5f5f5"      # Card/panel background

  # Text colors
  text: "#333333"         # Primary text
  textSecondary: "#666666" # Secondary text

  # Status colors
  error: "#f44336"
  warning: "#ff9800"
  info: "#2196f3"
  success: "#4caf50"

darkMode:
  enabled: true
  colors:
    primary: "#90caf9"
    secondary: "#f48fb1"
    accent: "#ce93d8"
    background: "#121212"
    surface: "#1e1e1e"
    text: "#ffffff"
    textSecondary: "#aaaaaa"

layout:
  maxWidth: "1200px"
  borderRadius: "8px"
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
  headerHeight: "64px"

features:
  darkMode: true           # Enable dark mode toggle
  exportEnabled: true      # Allow exporting search results
  advancedFilters: true    # Show advanced filter options
  keyboardShortcuts: true  # Enable keyboard shortcuts
  realtimeSearch: true     # Search as you type
  searchHistory: true      # Remember recent searches

# Preset themes (uncomment to use)
# preset: "google"  # Options: default, google, github, enterprise, dark